/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameAcceuil;

import java.awt.Frame;

/**
 *
 * @author nourik
 */
public class FrameAcceuil extends javax.swing.JFrame {
    private int XDrag,YDrag;

    /**
     * Creates new form FrameAcceuil
     */
    public FrameAcceuil() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Button = new javax.swing.JButton();
        TextField = new javax.swing.JTextField();
        FondTextField = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        BExit = new javax.swing.JButton();
        BMin = new javax.swing.JButton();
        BarreHaut = new javax.swing.JLabel();
        Fond = new javax.swing.JLabel();
        FondBis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        Button.setBorder(null);
        Button.setContentAreaFilled(false);
        Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Button);
        Button.setBounds(630, 500, 165, 53);

        TextField.setBorder(null);
        TextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextField.setOpaque(false);
        getContentPane().add(TextField);
        TextField.setBounds(80, 500, 287, 51);
        getContentPane().add(FondTextField);
        FondTextField.setBounds(80, 500, 287, 51);

        jRadioButton1.setContentAreaFilled(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(410, 500, 20, 20);

        jRadioButton2.setContentAreaFilled(false);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(410, 530, 20, 20);

        BExit.setBorderPainted(false);
        BExit.setContentAreaFilled(false);
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });
        getContentPane().add(BExit);
        BExit.setBounds(800, 10, 20, 20);

        BMin.setBorderPainted(false);
        BMin.setContentAreaFilled(false);
        BMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMinActionPerformed(evt);
            }
        });
        getContentPane().add(BMin);
        BMin.setBounds(750, 10, 20, 20);

        BarreHaut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameAcceuil/BarreHaut.png"))); // NOI18N
        BarreHaut.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        BarreHaut.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarreHautMouseDragged(evt);
            }
        });
        BarreHaut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarreHautMousePressed(evt);
            }
        });
        getContentPane().add(BarreHaut);
        BarreHaut.setBounds(0, 0, 850, 45);
        getContentPane().add(Fond);
        Fond.setBounds(0, 0, 850, 600);
        getContentPane().add(FondBis);
        FondBis.setBounds(850, 0, 850, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BExitActionPerformed

    private void BMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMinActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_BMinActionPerformed

    private void BarreHautMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarreHautMousePressed
        this.XDrag = evt.getX();
        this.YDrag = evt.getY();
    }//GEN-LAST:event_BarreHautMousePressed

    private void BarreHautMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarreHautMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-this.XDrag, y-this.YDrag);
    }//GEN-LAST:event_BarreHautMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAcceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BExit;
    private javax.swing.JButton BMin;
    private javax.swing.JLabel BarreHaut;
    private javax.swing.JButton Button;
    private javax.swing.JLabel Fond;
    private javax.swing.JLabel FondBis;
    private javax.swing.JLabel FondTextField;
    private javax.swing.JTextField TextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
